### ISSUE TITLE
Comment about the return value for `ProveNamespace` function does not correspond the code

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/nmt#123]
[Comment](https://github.com/celestiaorg/nmt/blob/4276d172f18c87ebdd18da0cc4b758f0dd164118/nmt.go#L182-L183) above `ProveNamespace` function stated that an error is returned when the requested nID is not in the tree's range. 

It appears that this is not aligned with the [comment and the code](https://github.com/celestiaorg/nmt/blob/4276d172f18c87ebdd18da0cc4b758f0dd164118/nmt.go#L211-L215) in the `ProveNamespace` function for that specific case. These do not mention or return an error (nill is returned).

**Comment by andrijamitrovic23** [comment]
Probably a new type of error should be added as it is done in the [ProveRange](https://github.com/celestiaorg/nmt/blob/4276d172f18c87ebdd18da0cc4b758f0dd164118/nmt.go#L172) function for an invalid range.

**Comment by rootulp** [comment]
@staheri14 do you know why ProveNamespace returns an EmptyRangeProof if the requested namespace is outside the range of the NMT? I would expect that an error is sufficient.

**Comment by rootulp** [comment]
Multiple options to resolve this issue:
1. https://github.com/celestiaorg/nmt/pull/167 is less controversial
2. https://github.com/celestiaorg/nmt/pull/166 takes the approach recommended in this issue by creating a new error

**Comment by staheri14** [comment]
> do you know why ProveNamespace returns an EmptyRangeProof if the requested namespace is outside the range of the NMT? I would expect that an error is sufficient because a user can determine that their requested namespace falls outside the bounds of the NMT by inspecting the NMT's min / max namespace. In other words, what value does the EmptyRangeProof add?

The godoc does not align with the implementation, and should be revised.
After conducting additional investigation, I think it may not be necessary to return an error when a query is made for a namespace ID that falls outside the range of the tree's name ID. Such a query is not an erroneous input and can be considered a reasonable request, for which an empty response would be appropriate. Therefore, I believe that revising the godoc would be sufficient.
