### ISSUE TITLE
Deprecate `master` in favor of `main`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/nmt#171]
https://github.com/github/renaming

**Comment by rootulp** [comment]
Note: when we tackle this we'll need to modify some Github workflows. Ex

https://github.com/celestiaorg/nmt/blob/33110363c1d9bc966c1a6f22fd6c35ff41f00b31/.github/workflows/go.yml#L5

**Comment by adlerjohn** [comment]
Protected branches will also need to be updated

**Comment by rootulp** [comment]
<img width="111" alt="Screenshot 2023-08-28 at 4 48 53 PM" src="https://github.com/celestiaorg/nmt/assets/3699047/90418ed9-8180-4d85-9a39-1398d2150ae5">

Since master is already protected, I think if we rename master to main, then main will remain protected but worth double checking when we tackle this.

**Comment by rootulp** [comment]
FYI I just renamed `master` => `main`. @celestiaorg/celestia-core 

![Screenshot 2024-04-17 at 2 19 59 PM](https://github.com/celestiaorg/nmt/assets/3699047/f54db6f4-969f-4870-8ea1-40c47e810df5)

**Comment by rootulp** [comment]
Confirmed branch protection rules apply to `main` now.
