### ISSUE TITLE
gobencher failure

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/nmt#204]
gobencher appears to fail on main: https://github.com/celestiaorg/nmt/runs/13789510043 and this PR: https://github.com/celestiaorg/nmt/pull/203/checks?check_run_id=13795230632

```
No benchmark results! rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 54.39.48.228:8888: connect: connection timed out"
```

**Comment by rootulp** [comment]
Tagging @elias-orijtech @odeke-em from Orjitech because https://dashboard.bencher.orijtech.com/ appears maintained by ya'll

**Comment by rootulp** [comment]
Proposal to disable gobencher b/c it's been failing consistently for 3+ weeks

**Comment by rootulp** [comment]
It's not a workflow in https://github.com/celestiaorg/nmt/tree/master/.github/workflows so it looks like a repo admin needs to disable the Github app on this repo. Tagging @MSevey

**Comment by MSevey** [comment]
> It's not a workflow in https://github.com/celestiaorg/nmt/tree/master/.github/workflows so it looks like a repo admin needs to disable the Github app on this repo. Tagging @MSevey

I think we talked about this in the past with Ismail, since it isn't blocking we figured we would just leave it on for when it gets fixed since it is a useful tool.  But it has been awhile so if the team feels like just removing it I can disable the app for the org. 

Let's revisit in slack to get a quick consensus and then we can action it.

**Comment by rootulp** [comment]
Closing b/c looks like gobencher was removed from this repo

<img width="510" alt="Screenshot 2023-06-21 at 1 42 34 PM" src="https://github.com/celestiaorg/nmt/assets/3699047/1ca2192e-cc02-48cb-8f81-f8b6dc06b92d">
