### ISSUE TITLE
Define String representation of IntervalDigest

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/nmt#21]
@liamsi suggested printing IntervalDigest as CID in a private discussion, however that may require additional `go-cid` dependency for the lib. Anyway, we should define a concrete representation to ensure proper test coverage in the parent repo.

**Comment by liamsi** [comment]
For context where this is coming from: the DA header will be part of the proposal soon (with https://github.com/lazyledger/lazyledger-core/issues/181), for debugging purposes the proposal can be logged out and a String() method will be called by the logger. My suggestion was mostly about adding a String representation for the DA header roots (row and col roots) as CIDs. This might be useful for debugging purposes, e.g. if we wanted the query a CID via an ipfs binary. 

That said, this could also be achieved without modifying the NMT library: we can simply transform the hashes into a Cid in LL core. 
Although nothing really speaks against making the NMT lib directly spit out CIDs I'm a bit hesitant as the concept of a Namespaced Merkle tree might be useful independent of LL and certainly independent of IPFS (Cids). I haven't seen any other project using it yet though. If we decide to make the library less general-purpose and more tied to LL-core, we can certainly make the NMT depend on CIDs as they already have a nice string representation for instance.
