### ISSUE TITLE
Investigating Snyk complaints about go.mod

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/nmt#225]
# Problem
Starting from this [PR](https://github.com/celestiaorg/nmt/pull/220), and following the addition of Snyk in the CIs, we have encountered failures in the CIs. These failures are occurring due to Snyk identifying 14 vulnerabilities in the go.mod changes.

For more details, please refer to the [comment](https://github.com/celestiaorg/nmt/pull/220#issuecomment-1640783084) made by @rootulp:

> Snyk claims this PR introduces 14 new vulnerabilities b/c the `go.mod` changes. I don't think we should block the PR on it though

This issue has been opened to track the problem and ensure that it is addressed, particularly if it is deemed to be a critical issue.

**Comment by rootulp** [comment]
## Screenshot

<img width="1479" alt="Screenshot 2023-07-18 at 3 20 27 PM" src="https://github.com/celestiaorg/nmt/assets/3699047/8c690956-ad13-401b-a2e2-5854de53c7cb">

there are more dependencies flagged by Snyk

**Comment by staheri14** [comment]
Based on this recent [test PR](https://github.com/celestiaorg/nmt/pull/243), It seems that Snyk has been disintegrated from this repo, if that is the case, then this issue is no longer needed and can be closed
ccing @rootulp  for confirmation

**Comment by rootulp** [comment]
yes please, good catch! Let's close as won't fix.
