### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/nmt#231]
## Context

https://github.com/celestiaorg/nmt/blob/33110363c1d9bc966c1a6f22fd6c35ff41f00b31/.github/workflows/go.yml#L16

is outdated because there exists a setup-go [v4.1.0](https://github.com/actions/setup-go/releases/tag/v4.1.0).

## Problem

Dependabot is not configured for this repo

## Proposal

Enable dependabot for this repo. Inspiration can be drawn from
- https://github.com/celestiaorg/celestia-app/blob/0d1750a40d34d2788b3f3a0a8d084f2dad76eb5c/.github/dependabot.yml
- https://github.com/celestiaorg/rsmt2d/blob/39f259f21a4254fa8fdf4b9131df777e1c7f0d3a/.github/dependabot.yml

**Comment by Chirag018** [comment]
@rootulp would like to work on this
