### ISSUE TITLE
Min/max definitions in diagram in readme don't match specs and implementation

### ISSUE THREAD

**Issue by oneeman** [celestiaorg/nmt#41]
If I'm understanding the diagram (https://github.com/celestiaorg/nmt/blob/6d5b99ddb71ae8f8c11d7a5fedc3b84532e949a7/imgs/example_4-leaves.png) correctly, it seems to have mistakes in how the mins and maxes are calculated.  For example:

```
min_2.0 = min(min_1.0, max_1.1)
```

Judging from the specs (https://github.com/celestiaorg/celestia-specs/blob/ec98170398dfc6394423ee79b00b71038879e211/src/specs/data_structures.md) and the implementation (https://github.com/celestiaorg/nmt/blob/6d5b99ddb71ae8f8c11d7a5fedc3b84532e949a7/hasher.go#L128-L131) it should instead say:

```
min_2.0 = min(min_1.0, min_1.1)
```

And analogously for all the other non-leaf min and max definitions in the diagram.

**Comment by liamsi** [comment]
Yeah, you are right. Thanks for catching this 🙏🏼  I'll regenerate the diagram or re-create it manually when I find some time (I used this branch of my trillian fork to generate the diagram initially: https://github.com/liamsi/trillian/tree/nmt_treetex).
