### ISSUE TITLE
Implement NMT in Rust + make it easy to use from other languages

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/nmt#84]
We got this feedback:
> Verifying NMT proofs will probably a common operation. It would be nice eventually to have an implementation in a language like C/C++/Rust that people could access via FFI/bindings.

I think we should prioritize this post-launch.

**Comment by rootulp** [comment]
> Implement NMT in Rust

https://github.com/Sovereign-Labs/nmt-rs

**Comment by adlerjohn** [comment]
Should this issue be closed in favor of the above repo (perhaps documenting in the readme that non-endorsed implementations in other languages exist?), or do we want to have an in-house implementation? Thoughts @liamsi @evan-forbes?

**Comment by evan-forbes** [comment]
at the minimum linking other nmt repos and their current status (ie maintained or feature complete etc) seems like a really good idea

**Comment by rootulp** [comment]
Closing this as done via https://github.com/celestiaorg/nmt/pull/229
