### ISSUE TITLE
feat: verify the range of the namespace IDs of left and right nodes in the Hasher 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/nmt#95]
# Problem
The [ `Hasher`](https://github.com/celestiaorg/nmt/blob/b04eea51d193f2fa33af6c017979a1516b6865ef/hasher.go#L155) implementation does not verify the range of namespace IDs in the left and right nodes with respect to each other, which is crucial for proper ordering of leaves based on their namespace IDs and for detecting invalidly constructed trees and proofs.

Quoting from Lazy Ledger paper:
> An adversarial consensus node may attempt to produce a block that contains a Merkle tree with children that are not ordered correctly. To prevent this, we can set a condition in nsHash such that there is no valid hash when leftMaxNs ≥ rightMinNs, and thus there would be no valid Merkle root for incorrectly ordered children

The issue was identified as part of https://github.com/celestiaorg/celestia-app/issues/1296
# Acceptance Criteria
- [ ] To modify the [`Hasher`](https://github.com/celestiaorg/nmt/blob/b04eea51d193f2fa33af6c017979a1516b6865ef/hasher.go#L155) implementation by incorporating this additional namespace ID range check for the supplied children nodes. Possibly, the `Hasher` can return an error for invalid inputs. Subsequent refactor needs to take place to properly consume this change.

**Comment by liamsi** [comment]
Somewhat related. I think these functions can also be deleted: https://github.com/celestiaorg/nmt/issues/87#issuecomment-1355165925

**Comment by staheri14** [comment]
> Somewhat related. I think these functions can also be deleted: [#87 (comment)](https://github.com/celestiaorg/nmt/issues/87#issuecomment-1355165925)

@liamsi I addressed your comment in a separate pull request https://github.com/celestiaorg/nmt/pull/103, rather than the one that is closing this issue. Mainly in favour of creating small, single-purpose commits that would make it easier to revert changes if necessary in the future.
